spring:
  r2dbc:
    url: r2dbc:mysql://devsu-mysql-1:3306/devsudb?tlsVersion=TLSv1.2
    username: root
    password: root
    options:
      connectTimeout: 30000ms
      ssl: false
  kafka:
    bootstrap-servers: kafka:9092
  application:
    name: business-client-management-service
  main:
    web-application-type: reactive
server:
  error:
    include-stacktrace: never